language: c

compiler:
    - clang
    - gcc

jobs:
    include:
    - os: linux
      disk: bionic
    - os: linux
      dist: xenial
    - os: linux
      dist: trusty
    - os: osx

env:
    global:
        - PATH="/usr/bin:/usr/local/bin:$PATH"

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" AND "$TRAVIS_DIST_NAME"="trusty" ]; then sudo apt-get install -qq libfuse-dev libpolarssl-dev ruby-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" AND "$TRAVIS_DIST_NAME"="xenial" ]; then sudo apt-get install -qq libfuse-dev libmbedtls-dev ruby-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "linux" AND  "$TRAVIS_DIST_NAME"="bionic" ]; then sudo apt-get install -qq libfuse-dev libmbedtls-dev ruby-dev; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install -v Caskroom/cask/osxfuse; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./src/mbed_install.sh; fi

install:
    - cmake .
    - make VERBOSE=1
    - sudo make install

script:
    - make travis-test

notifications:
    email:
        recipients:
            - aorimn@gmail.com

        on_success: always
        on_failure: always
